#!/usr/bin/env bash
set -ux
version_sbt=$(cat version.sbt)
version=$(echo $version_sbt | perl -pe 's/.*"(.*)".*/$1/')
file_name=estoril-assembly-$version.jar
echo "Building $file_name"
sbt assembly
mkdir -p dist/assembly
cp -a {target/scala-2.12,dist/assembly}/$file_name
echo "Commiting $version"
git commit
echo "Incrementing patch version for next development"
version_sbt=$(cat version.sbt | perl -pe 's/(\d+)(?=")/$1+1/ge')
echo $version_sbt > version.sbt
echo "version.sbt => $version_sbt"
